---
title: "Ejercicio 1 (b)"
author: "Gloria"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```
An치lisis de la normalidad multivariada - Test de Henze Zirkler

```{r, echo=TRUE}
#An치lisis de normalidad bivariada 
library(MVN)
attach(grasacerdos)
peso_egd=data.frame(PV,EGD)
#Usamos Test Henze-Zirkler para evaluar normalidad multivariada (bivariada en este caso)
respuesta_testHZ<-mvn(peso_egd , mvnTest = "hz")
print(respuesta_testHZ$multivariateNormality)
```
El test da por resultado que las variables son normales bivariadas.

La correlaci칩n entre ambas variables es:

```{r}
cor(PV, EGD, method= "pearson")
```
La correlaci칩n entre las variables es baja .

```{r}
cor.test(PV, EGD,method="pearson")
```
No es necesario aplicar el coeficiente de Spearman pues se satisfacen los supuestos. 

```{r}
library(corrplot)
M= cor(grasacerdos)
M
```


```{r}
v<- var(grasacerdos)
```
```{r}
numerador<- var(grasacerdos)[2,1]
denominador <- sqrt(v[1,1]) * sqrt(v[2,2])
correlacion<- numerador/denominador
correlacion
```


